[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/atim-starship.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:starship.repo
SandboxTrees=repos/scottames-ghostty.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:scottames:ghostty.repo
SandboxTrees=repos/wezfurlong-wezterm-nightly.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:wezfurlong:wezterm-nightly.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:atim:starship
Repositories=copr:copr.fedorainfracloud.org:scottames:ghostty
Repositories=copr:copr.fedorainfracloud.org:wezfurlong:wezterm-nightly

[Content]
Packages=
    starship
    ghostty
    wezterm
