[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/docker-ce.repo:/etc/yum.repos.d/docker-ce.repo

[Distribution]
Repositories=docker-ce-stable

[Content]
Packages=
    docker-ce
    docker-ce-cli
    containerd.io
    docker-buildx-plugin
    docker-compose-plugin
